### ISSUE TITLE
How to use after installation?

### ISSUE THREAD

**Issue by caoxuCarlos** [laomocode/fcitx-sogouimebs#1]
I am in Ubuntu 20.04I 've installed sogouimebs.deb, and reboot. But Fcitx icon just disappear from my top bar. Sogou input doesn't work, please help.

**Comment by caoxuCarlos** [comment]
这个方法可以解决 Ubuntu 20.04 LTS 的中文输入问题. 

1. 做好重启好几次的心理准备.

2. 进入https://github.com/laomocode/fcitx-sogouimebs/releases    在最下面下载 sogouimebs.deb

3. `sudo dpkg -i sogouimebs.deb`

4. 进行 Fcitx 的配置, 请参考 https://leimao.github.io/blog/Ubuntu-Gaming-Chinese-Input/ (这里可能会需要在 ibus 和 fcitx 之间切换, 并且好几次)

5. 如果切换到了 fcitx 而且一切正常, 那么在开机以后请在右上角点开 fcitx 图标, 在 configue 里面的 input method 中选择. 

6. 其他的建议

   > 这个版本的搜狗输入法并没有 "在中文下使用英文标点的功能", 如果想实现这个功能: 
   >
   > 1. 在搜狗输入法的设置里面打开 `shift+.` 的全角半角切换
   > 2. 在设置当中把中英文快捷键的切换改成 `无`
   > 3. 在 fcitx configure 中将输入法之间的切换改成 `shift`
   >
   > 这样达到的效果是: 
   >
   > 在打开搜狗输入法, 并且把标点设置成半角以后, 点击 shift 就切换到了默认的英文输入法(但是感觉好像只是在搜狗输入法里切换了中英文), 在换回到中文的时候标点符号还是半角. 
   >
   > 参考阅读: https://blog.csdn.net/win_turn/article/details/53637293

**Comment by laomocode** [comment]
老哥，你操作有点迷呀

而且补充一下，Gnome桌面对Fcitx框架支持不好，还是用ibus更好一些

**Comment by caoxuCarlos** [comment]
哈哈是的, 这个方法确实存在问题 ---- 在转换的时候经常不小心就卡死了---- 我不知道问题是出在 1) fcitx 输入法相互转换的问题 还是 2) 这个版本的搜狗拼音的问题. 现在虽然还是在用 fcitx, 但是改用了 google pinyin, 比预想中的感觉要好. 

老哥你有没有推荐的 ibus 中文输入法啊~
