### ISSUE TITLE
unnecessary file (/sogouimebs.deb; /..deb) on version 2.0.0.38 

### ISSUE THREAD

**Issue by id9502** [laomocode/fcitx-sogouimebs#2]
There are two redundant files "/sogouimebs.deb" and "/..deb" installed into root dir "/" after installing the package (ver 2.0.0.38), which seems to be accidentally added into the release package.
Could you please remove those two files from the final package on the next release?

**Comment by laomocode** [comment]
Thank you your feedback.This is Bug.Next Debian version will fix it.
