### ISSUE TITLE
请问pkg.tar.xz格式的包该怎么安装呢？

### ISSUE THREAD

**Issue by caixxiong** [laomocode/fcitx-sogouimebs#5]

**Comment by laomocode** [comment]
你是什么发行版的

**Comment by caixxiong** [comment]
ubuntu 20.04

**Comment by laomocode** [comment]
能装就怪了，这个是ArchLinux版本的
Ubuntu版链接：http://archive.ubuntukylin.com/ukui/pool/main/s/sogouimebs/sogouimebs_2.0.0.38+0428.1_amd64.deb
